name: Deploy FastAPI para a Azure

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      # 1. Instala o Poetry para isolar e rodar os testes com segurança
      - name: Instalar o Poetry
        run: |
          pipx install poetry

      - name: Instalar dependências no ambiente do Poetry
        run: |
          poetry install --no-root

      # 2. Executa a sua suíte de testes
      - name: Executar testes com Pytest
        run: |
          poetry run pytest

      # 3. O SEGREDO: O GitHub instala os pacotes do requirements.txt dentro de uma pasta local antes do deploy
      - name: Preparar empacotamento de produção
        run: |
          pip install -r requirements.txt --target=.

      # 4. Envia o pacote completo (Código + Bibliotecas juntas)
      - name: Fazer deploy para o Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'zelda'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .